<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Ordering.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Npgsql.EntityFrameworkCore.PostgreSQL"/>
    <PackageReference Include="Carter"/>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
    <PackageReference Include="Aspire.Keycloak.Authentication"/>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp"/>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces"/>
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Aspire\ServiceDefaults\ServiceDefaults.csproj"/>
    <ProjectReference Include="..\Ordering.Application\Ordering.Application.csproj"/>
    <ProjectReference Include="..\Ordering.Infrastructure\Ordering.Infrastructure.csproj"/>
  </ItemGroup>

</Project>
