<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-Basket.API.MigrationService-bb5482fc-1490-403f-b23b-4d575d50477f</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Hosting" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Aspire\ServiceDefaults\ServiceDefaults.csproj" />
      <ProjectReference Include="..\Basket.API\Basket.API.csproj" />
    </ItemGroup>
</Project>
