<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Keycloak.Authentication"/>
    <PackageReference Include="Aspire.Microsoft.Extensions.Configuration.AzureAppConfiguration"/>
    <PackageReference Include="FluentValidation"/>
    <PackageReference Include="FluentValidation.AspNetCore"/>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
    <PackageReference Include="Mapster"/>
    <PackageReference Include="MediatR"/>
    <PackageReference Include="Microsoft.AspNetCore.Authentication"/>
    <PackageReference Include="Microsoft.FeatureManagement"/>
  </ItemGroup>

</Project>
