<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Catalog.API.MigrationService-e18417b6-be03-41f4-8577-99aab6f4b1dc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Aspire\ServiceDefaults\ServiceDefaults.csproj"/>
    <ProjectReference Include="..\..\Services\Catalog\Catalog.API\Catalog.API.csproj"/>
  </ItemGroup>
</Project>
