<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-Catalog.API.MigrationService-23d76e64-7765-4bb4-bba3-655db10de4e9</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.8"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Catalog.API\Catalog.API.csproj"/>
    </ItemGroup>
</Project>
