<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Basket.API.MigrationService-9627d922-ce0e-4dd1-8509-de783300e2d9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Aspire\ServiceDefaults\ServiceDefaults.csproj"/>
    <ProjectReference Include="..\..\Services\Basket\Basket.API\Basket.API.csproj"/>
  </ItemGroup>
</Project>
